### ISSUE TITLE
Mostrar votación previa

### ISSUE THREAD

**Issue by jorgecasar** [manufosela/codemotionVoting#1]
No hay forma de revisar las votaciones, cuando vuelves a una charla ya votada no se ve que votación diste.

**Comment by rafacapa** [comment]
Como consecuencia, si te dejas alguna sin votar luego no hay forma de saber cual es...

**Comment by manufosela** [comment]
Done!

**Comment by Borjagodoy** [comment]
No dais tiempo a nada sois unos maquinas jaja
