### ISSUE TITLE
Ordenación de resultados

### ISSUE THREAD

**Issue by Borjagodoy** [manufosela/codemotionVoting#3]
Tengo una PR preparada por si veis oportunos el tener ordenadas las votaciones por el puesto que ocupan en función a los votos.

Espero respeusta :)

**Comment by manufosela** [comment]
Claro Borja!! Encantado!! :)
Abriste branch? Crea la PR y la subo :D

**Comment by Borjagodoy** [comment]
Si me das 10 min subo un fix al componente de estrella y también que se visualicen los votos que ya hiciste

**Comment by manufosela** [comment]
Eso lo tengo ya hecho. Y acabo de aprobar una mega PR con mejoras tb

**Comment by manufosela** [comment]
Borja, en la PR que ha hecho Jorge del Casar está la ordenación tb... Se nos ha adelantado a todos :/

**Comment by manufosela** [comment]
Paso a cerrarla

**Comment by Borjagodoy** [comment]
ya lo vi jajaj
